version: "3.9"
services:
  mainnetwork:
    image: alpine:3.14
    command: ["tail", "-f", "/dev/null"]
  db:
    image: postgres:13-alpine
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./database/script:/script:ro
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  backend:
    image: python:3.9
    working_dir: /app
    command: ["./start.sh"]
    volumes:
      - ./backend:/app:delegated
    environment:
      - DB_SCHEMA=akvoapp
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DEBUG=True
      - SECRET_KEY=secret
    depends_on:
      - db
  frontend:
    image: akvo/akvo-node-18-alpine:20250306.055839.23cadbd
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    depends_on:
      - backend
volumes:
  pg-data:
