---
services:
  frontend_build:
    image: akvo/akvo-node-18-alpine:20230831.105309.b9593b7
    container_name: frontend_build
    env_file: "./app.env"
    working_dir: /app
    environment:
      - CI_COMMIT=${CI_COMMIT}
    command:
      - /bin/bash
      - -c
      - |
        mv frontend/next.config.prod.mjs frontend/next.config.mjs
        echo 'WEBDOMAIN=${WEBDOMAIN}' >> frontend/.env
        echo 'NEXT_AUTH_SECRET_KEY=${SECRET_KEY}' >> frontend/.env
        cd frontend && yarn install --no-progress --frozen-lock && yarn build
    volumes:
      - ..:/app:delegated