CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';

CREATE DATABASE ${DB_SCHEMA}
WITH OWNER = ${DB_USER}
     template = template0
     ENCODING = 'UTF-8'
     LC_COLLATE = 'en_US.UTF-8'
     LC_CTYPE = 'en_US.UTF-8';

\c ${DB_SCHEMA}

CREATE EXTENSION IF NOT EXISTS ltree WITH SCHEMA public; 